### ISSUE TITLE
test_copy_if build failure

### ISSUE THREAD

**Issue by d-meiser** [boostorg/compute#8]
I get the following error message:

[ 32%] Building CXX object test/CMakeFiles/test_copy_if.dir/test_copy_if.cpp.o
cd /home/scratch/boost.compute/build/test && /usr/bin/c++   -DBOOST_COMPUTE_DEBUG_KERNEL_COMPILATION -DBOOST_TEST_DYN_LINK -g -I/usr/local/cuda/include -I/home/dmeiser/software/boost-1_53_0-ser/include -I/home/scratch/boost.compute/include -I/home/scratch/boost.compute/test/../include    -o CMakeFiles/test_copy_if.dir/test_copy_if.cpp.o -c /home/scratch/boost.compute/test/test_copy_if.cpp
/home/scratch/boost.compute/include/boost/compute/functional/geometry.hpp: In member function ‘void clip_points_below_plane::test_method()’:
/home/scratch/boost.compute/include/boost/compute/functional/geometry.hpp:21: error: ‘template<class T> class boost::compute::dot’ is not a function,
/home/scratch/boost.compute/include/boost/compute/lambda/functional.hpp:222: error:   conflict with ‘template<class Arg1, class Arg2> const typename boost::proto::result_of::make_expr<boost::proto::tagns_::tag::function, boost::compute::lambda::detail::dot_func, const Arg1&, const Arg2&, void, void, void, void, void, void, void, void, void>::type boost::compute::lambda::dot(const Arg1&, const Arg2&)’
/home/scratch/boost.compute/test/test_copy_if.cpp:106: error:   in call to ‘dot’

This could be a gcc issue (I'm trying to build with gcc 4.4.6). Will try to build with newer gcc and clang
